import sys, re
sys.stdout.reconfigure(encoding='utf-8')

DESC = {
"PP405": "PP405 is a small-molecule MPC (mitochondrial pyruvate carrier) inhibitor developed by Pelage Pharmaceuticals for androgenetic alopecia. It reactivates dormant hair follicle stem cells — not by blocking DHT like finasteride. Phase 2 trials showed statistically significant new hair growth without systemic hormonal effects. The topical formulation penetrates the scalp and acts locally on follicle stem cell metabolism. OTC products using the 'PP405' name are unrelated compounds.",
"Retatrutide": "Retatrutide (LY3437943) is a triple agonist targeting GLP-1, GIP, and glucagon receptors — the only triple agonist in late-stage clinical trials as of 2024. Phase 2 trials produced 24% body weight reduction at 48 weeks, surpassing tirzepatide. The glucagon component adds thermogenesis and liver fat reduction on top of appetite suppression. It significantly improved cardiovascular risk markers, liver enzymes, and insulin sensitivity. Titration is essential — starting too high causes severe GI distress.",
"Tirzepatide": "Tirzepatide (Mounjaro/Zepbound) is FDA-approved for type 2 diabetes and obesity. It is a dual GIP/GLP-1 receptor agonist — the GIP component amplifies insulin secretion and may reduce GLP-1 side effects, contributing to superior tolerability. SURMOUNT-1 trial showed 22.5% average body weight loss at 72 weeks. It also improves sleep apnea, fatty liver disease, and cardiovascular outcomes. Available commercially — no need for research-grade sourcing for most users.",
"Semaglutide": "Semaglutide (Ozempic/Wegovy) is the most widely used GLP-1 receptor agonist worldwide. It slows gastric emptying, reduces appetite via hypothalamic signaling, and improves insulin secretion. The STEP 1 trial showed 14.9% average weight loss at 68 weeks. SELECT trial demonstrated a 20% reduction in major cardiovascular events independent of weight loss. Half-life of ~7 days allows once-weekly dosing. Must be titrated slowly to avoid nausea, vomiting, and gastroparesis.",
"Semax": "Semax is a synthetic analogue of ACTH(4-7) developed in Russia for stroke recovery and cognitive enhancement. It dramatically upregulates BDNF, VEGF, and NGF in the brain — making it one of the most potent neurogenesis-promoting compounds available. Research shows benefits in attention, memory consolidation, anxiety reduction, and neuroprotection after ischemic injury. Intranasal bioavailability is high. Cycling is recommended to maintain BDNF receptor sensitivity.",
"Na Semax": "N-Acetyl Semax is an acetylated version of Semax with greater lipophilicity, improved blood-brain barrier penetration, and longer duration of action. The acetylation protects the peptide from enzymatic breakdown, making effective doses lower than standard Semax. Users report stronger and more sustained cognitive enhancement with a flatter, longer effect curve rather than a sharp peak.",
"Selank": "Selank is a synthetic heptapeptide analogue of tuftsin developed by the Institute of Molecular Genetics in Russia. It modulates GABAergic transmission and upregulates BDNF, producing anxiolytic effects comparable to benzodiazepines without sedation, tolerance, or withdrawal. Unlike benzos, it does not downregulate GABA receptors. Intranasal administration produces effects within minutes. Particularly useful for anxiety-driven cognitive impairment.",
"Na Selank": "N-Acetyl Selank is the acetylated, more bioavailable form of Selank with a significantly longer half-life. The N-acetylation dramatically increases stability in nasal tissue, allowing lower doses to achieve the same effect. Particularly effective for generalized anxiety with cognitive impairment. Does not cause sedation or motor impairment at therapeutic doses. Research also suggests immunomodulatory effects — normalizing interferon-alpha and interleukin balance during psychological stress.",
"Cagrilintide": "Cagrilintide is a long-acting amylin analogue (once-weekly dosing) that targets the amylin receptor to slow gastric emptying and suppress appetite through a mechanism completely distinct from GLP-1. When combined with semaglutide (CagriSema), trials showed up to 25% body weight reduction — exceeding either drug alone. The amylin pathway provides a complementary satiety signal that reduces food reward and preference for calorie-dense foods. Currently in Phase 3 trials for obesity.",
"Mazdutide": "Mazdutide (IBI362) is a dual GLP-1/glucagon receptor agonist approved in China and in Phase 3 trials globally. The glucagon component increases thermogenesis and reduces liver fat — addressing NAFLD more effectively than GLP-1 monotherapy. Phase 2 data showed up to 14% weight loss plus significant liver fat reduction, making it particularly promising for patients with obesity combined with metabolic liver disease.",
"Survodutide": "Survodutide (BI 456906) is a glucagon/GLP-1 dual receptor agonist developed by Boehringer Ingelheim in Phase 3 trials for obesity and NASH. Its high glucagon activity drives liver fat mobilization, making it potentially superior to GLP-1-only agents for hepatic steatosis. In Phase 2, it outperformed placebo on liver fat content, liver stiffness, and body weight — positioning it as a metabolic liver disease treatment as well as a weight loss drug.",
"5-Amino-1MQ": "5-Amino-1MQ is a selective, cell-permeable NNMT (nicotinamide N-methyltransferase) inhibitor. NNMT is overexpressed in fat tissue and drives adipogenesis and metabolic dysfunction. By blocking NNMT, it raises SAM levels, activating SIRT1 and the NAD+ salvage pathway — mimicking caloric restriction at the cellular level. Research in mice showed significant fat mass reduction without muscle loss or caloric restriction. Oral bioavailability makes it practical.",
"VIP": "Vasoactive intestinal peptide (VIP) is a pleiotropic neuropeptide with potent anti-inflammatory, immunomodulatory, and vasodilatory properties. It inhibits TNF-alpha, IL-6, and IL-12 while promoting anti-inflammatory IL-10. Research has shown benefit in mast cell activation syndrome (MCAS), dysautonomia, pulmonary arterial hypertension, and inflammatory bowel disease. Its short half-life (1-2 minutes) makes delivery timing critical. Some protocols use intranasal VIP to bypass systemic clearance.",
"BPC-157": "Body Protection Compound-157 is a synthetic pentadecapeptide derived from a protective gastric protein. It is one of the most extensively researched healing peptides, with robust evidence for accelerating tendon, muscle, ligament, bone, and gut tissue repair. Mechanisms include upregulation of growth hormone receptors, VEGF-driven angiogenesis, nitric oxide modulation, and anti-inflammatory effects. BPC-157 has been shown to reverse NSAID-induced gut damage, heal intestinal fistulas, and dramatically accelerate surgical wound recovery. No serious adverse effects in any study to date.",
"TB-500": "Thymosin Beta-4 (TB-500) is a synthetic analogue of the naturally occurring thymosin beta-4 peptide, found in high concentrations at injury sites. Its primary mechanism is actin sequestration — by binding G-actin, it modulates cell migration and differentiation at wound sites. It upregulates VEGF and matrix metalloproteinases to drive angiogenesis and tissue remodeling. Particularly effective for chronic injuries — tendons, ligaments, and cardiac tissue that respond slowly to standard treatment. Often stacked with BPC-157 for synergistic recovery.",
"Abaloparatide": "Abaloparatide (Tymlos) is an FDA-approved PTHrP(1-34) analogue for postmenopausal osteoporosis. Unlike teriparatide, it preferentially binds the RG conformation of PTH1R, producing a stronger anabolic bone response with less calcium mobilization — lower hypercalcemia risk. Clinical trials showed 86% reduction in vertebral fracture risk and 43% reduction in non-vertebral fractures. Maximum treatment duration is 18 months due to osteosarcoma risk observed in lifetime rodent studies.",
"Testagen": "Testagen is a tetrapeptide bioregulator (Lys-Glu-Asp-Gly) developed by Vladimir Khavinson targeting the male reproductive system and testosterone production. Bioregulator peptides work epigenetically — binding to specific DNA promoter regions to restore age-related gene expression decline. Testagen supports natural testosterone biosynthesis pathways without acting as exogenous testosterone. Used in the Khavinson anti-aging protocol in 10-day courses twice yearly.",
"Teriparatide": "Teriparatide (Forteo) is recombinant PTH(1-34), FDA-approved for osteoporosis in patients at high fracture risk. Unlike bisphosphonates (which prevent bone loss), teriparatide stimulates new bone formation — it is the only anabolic bone treatment available. It activates PTH1R on osteoblasts, promoting bone matrix production. Clinical trials increased lumbar spine BMD by 9.7% and reduced vertebral fractures by 65%. Maximum 24 months of use due to theoretical osteosarcoma risk.",
"AOD-9604": "AOD-9604 is a modified fragment of human growth hormone (hGH176-191) with a tyrosine group for stability. Unlike full HGH, AOD-9604 does not affect IGF-1 or blood glucose, making it safe for diabetics. It stimulates fat breakdown (lipolysis) and inhibits fat formation (lipogenesis) specifically in adipose tissue by mimicking the metabolic-regulating portion of the GH molecule. Particularly effective when injected fasted. Limited muscle-building effect — primarily a fat loss compound.",
"Hexarelin": "Hexarelin is one of the most potent growth hormone releasing peptides, producing the highest GH peak of any GHRP but also causing the most pronounced cortisol and prolactin elevation. Unique among GHRPs for its direct cardiac protective effects — independent of GH release, hexarelin activates CD36 receptors on cardiac muscle, reducing oxidative stress and promoting cardiomyocyte survival. Research in heart failure models showed significant functional improvement. Desensitization occurs quickly — strict cycling is essential.",
"HGH Fragment 176-191": "HGH Fragment 176-191 is the isolated C-terminal fragment of human growth hormone responsible for fat metabolism. It activates the same lipolytic pathway as full-length HGH without triggering IGF-1 production or affecting insulin sensitivity — useful for fat loss without the diabetes risk of full HGH. Twice-daily injections fasted maximize adipose activation. No anabolic effect — purely metabolic.",
"PT-141": "PT-141 (Bremelanotide) is a melanocortin receptor agonist (MC1R/MC4R) and the first FDA-approved treatment for hypoactive sexual desire disorder (HSDD) in premenopausal women. Unlike phosphodiesterase inhibitors, PT-141 works centrally — activating neural pathways in the hypothalamus responsible for sexual arousal, not just peripheral blood flow. This means it works for both physiological and desire-based dysfunction. Onset is 30-60 minutes; effects last 6-12 hours. Nausea and transient blood pressure increase are the main side effects.",
"PE-22-28": "PE-22-28 is a synthetic peptide derived from the Spadin peptide, designed to inhibit TREK-1 potassium channels in the brain. TREK-1 overactivity is associated with depression, and PE-22-28 blocks it with high selectivity — producing rapid antidepressant effects in rodent models resistant to standard SSRIs. It also promotes hippocampal neurogenesis via BDNF upregulation, suggesting effects on neuroplasticity rather than just monoamine modulation. Currently research-stage; intranasal delivery preferred for CNS access.",
"Kisspeptin": "Kisspeptin is the endogenous neuropeptide that serves as the master regulator of the hypothalamic-pituitary-gonadal (HPG) axis. It stimulates GnRH release from the hypothalamus, driving LH and FSH secretion, ultimately stimulating testosterone (men) or estrogen (women) production. Being studied for hypogonadism, fertility treatment, and HPG axis restoration post-anabolic steroid use. Pulsatile administration is critical — continuous exposure causes receptor desensitization and paradoxical LH suppression.",
"Epitalon": "Epitalon (Epithalon) is a synthetic tetrapeptide (Ala-Glu-Asp-Gly) developed by Khavinson with over 100 published papers. Its primary mechanism is activation of telomerase — the enzyme that elongates telomeres and slows cellular aging. Animal studies showed significant lifespan extension and reduced cancer incidence. Human trials in elderly subjects showed improved melatonin regulation, sleep quality, immune function, and antioxidant status. Used in 10-day courses twice yearly.",
"Na Epitalon": "N-Acetyl Epitalon is the acetylated derivative of Epitalon with improved membrane permeability and intranasal bioavailability. The acetylation prevents rapid enzymatic degradation, allowing more peptide to reach target tissues. Mechanisms are identical to standard Epitalon — telomerase activation, melatonin pathway support, and epigenetic gene expression restoration. Some users prefer the intranasal route for CNS delivery of its pineal-targeting effects.",
"Melanotan I": "Melanotan I (afamelanotide) is a synthetic alpha-MSH analogue that activates MC1R receptors on melanocytes, stimulating eumelanin (dark pigment) production throughout the skin. FDA-approved (as Scenesse) for erythropoietic protoporphyria — a rare light sensitivity disorder. Its melanogenesis effect is systemic and UV-exposure-dependent. Unlike MT-II, it has minimal effect on sexual arousal due to lower MC3R/MC4R affinity. Side effects are primarily nausea and facial flushing.",
"Melanotan II": "Melanotan II is a non-selective melanocortin receptor agonist (MC1R-MC4R) that produces tanning, sexual arousal, appetite suppression, and fat loss — all from MC4R activation. The tanning effect is robust and UV-exposure-dependent. Significant nausea at standard doses — subcutaneous microdosing minimizes this. Short half-life means effects are acute. Cycling required to avoid receptor desensitization.",
"CJC-1295 DAC": "CJC-1295 with DAC (Drug Affinity Complex) is a GHRH analogue conjugated to a linker that allows it to bind albumin in the bloodstream — extending half-life from minutes to 6-8 days. This creates a sustained elevation in baseline GH levels rather than a sharp pulse. Once-weekly dosing is sufficient. IGF-1 levels rise significantly with extended use. Best stacked with a GHRP (like Ipamorelin) to produce both the peak pulse and elevated baseline simultaneously.",
"CJC-1295 No DAC": "CJC-1295 without DAC (also called Mod GRF 1-29) is a GHRH analogue with a 30-minute half-life — closely mimicking natural GHRH pulses. It amplifies the GH pulse magnitude when timed correctly, particularly before sleep. Without the DAC linker, it does not cause prolonged GH elevation. It synergizes powerfully with GHRPs — the combination produces 4-10x the GH pulse of either peptide alone.",
"CJC/Ipamorelin 5/5": "A premixed blend of 5mg CJC-1295 (no DAC) and 5mg Ipamorelin — the most commonly used GH protocol combination. CJC-1295 stimulates GHRH receptors to amplify pulse magnitude; Ipamorelin activates ghrelin receptors to trigger GH release. Together they produce synergistic GH output significantly greater than either alone. Minimal cortisol, prolactin, or appetite effects. Best injected before sleep and optionally pre-workout.",
"CJC/Ipamorelin 6/11": "A higher-ratio blend with 6mg CJC-1295 and 11mg Ipamorelin per vial. The higher Ipamorelin load produces stronger GH pulses while maintaining the clean side effect profile Ipamorelin is known for. Popular for body recomposition cycles where stronger GH secretion is desired without switching to more aggressive GHRPs like GHRP-2 or Hexarelin. Still does not meaningfully elevate cortisol or prolactin at these doses.",
"CJC/Ipamorelin 10/10": "The highest standard blend ratio — 10mg CJC-1295 and 10mg Ipamorelin. Reserved for experienced peptide users seeking maximum GH output without pharmaceutical HGH. Produces very strong combined GH stimulation. More likely to cause water retention and potential appetite effects at high frequencies. Used in 8-12 week cycles with 4-week breaks. IGF-1 monitoring recommended.",
"GHRP-2": "GHRP-2 is a potent synthetic hexapeptide GH secretagogue that activates the ghrelin/GHS receptor with high affinity. It produces strong GH pulses but also significantly elevates cortisol and prolactin — a key distinction from cleaner GHRPs. The cortisol elevation makes GHRP-2 suboptimal for fat loss phases but potentially useful for immune support and recovery. It also stimulates appetite strongly. For maximum GH output in muscle-building protocols, GHRP-2 stacked with a GHRH analogue is highly effective.",
"GHRP-6": "GHRP-6 is the first synthetic GHRP studied extensively in humans. Its most notable side effect is intense appetite stimulation — making it counterproductive for fat loss but useful in bulking phases or for those with poor appetite. It also elevates cortisol and prolactin. Three-times-daily injection schedule is necessary due to its short half-life. The GH pulse quality is high but the appetite effect limits practical use for many.",
"Tesamorelin": "Tesamorelin (Egrifta) is an FDA-approved synthetic GHRH analogue for HIV-associated lipodystrophy — specifically visceral fat accumulation caused by antiretroviral therapy. It produces highly targeted visceral fat reduction by raising IGF-1 and GH, with Phase 3 data showing 15-18% reduction in visceral adipose tissue. Superior specificity for visceral fat compared to other GH-axis peptides. Daily injection required. Significantly raises IGF-1 levels — monitoring important for those with cancer risk factors.",
"MOTS-C": "MOTS-C is a mitochondria-encoded peptide discovered by Pinchas Cohen at USC. It is released from mitochondria in response to metabolic stress and acts as a mitokine — traveling to muscle and the nucleus to regulate glucose metabolism and insulin sensitivity. Exercise raises MOTS-C levels naturally. Exogenous MOTS-C improved insulin sensitivity, prevented diet-induced obesity, and improved physical performance in aging mice. It activates AMPK and creates a metabolic state similar to exercise. One of the most promising longevity peptides.",
"SS-31": "SS-31 (Elamipretide/Bendavia) is a mitochondria-targeting tetrapeptide that selectively concentrates in the inner mitochondrial membrane where it stabilizes cardiolipin — critical for cristae structure and electron transport chain efficiency. By preserving cardiolipin integrity, SS-31 reduces mitochondrial ROS, restores ATP production, and prevents mitochondrial swelling. In Phase 2/3 trials for heart failure with preserved ejection fraction (HFpEF). Research applications include aging, sarcopenia, kidney disease, and neurodegeneration.",
"Ipamorelin": "Ipamorelin is the cleanest and most selective growth hormone releasing peptide available. Unlike GHRP-2 and GHRP-6, it activates the ghrelin receptor with high selectivity without significantly raising cortisol, prolactin, or appetite — making it the standard recommendation for first GH peptide protocols. It produces a clean GH pulse closely mimicking natural pulsatile GH secretion. Best results come from stacking with CJC-1295 (no DAC) before sleep. Long-term use is considered safer than more potent GHRPs.",
"Thymosin Alpha-1": "Thymosin Alpha-1 (TA1/Zadaxin) is a synthetic 28-amino acid peptide derived from thymosin fraction 5, approved in over 40 countries for hepatitis B, hepatitis C, and as a cancer treatment adjuvant. It is the primary immunomodulatory peptide produced by the thymus gland. TA1 activates dendritic cells, NK cells, and T-helper cells, and upregulates MHC class II expression — enhancing the immune system's ability to identify and eliminate pathogens and abnormal cells. Used in long COVID protocols, chronic viral infections, and cancer support.",
"Thymulin": "Thymulin (FTS) is a naturally occurring thymic peptide that requires zinc for its biological activity. Produced by thymic epithelial cells, it regulates T-cell maturation and differentiation. Thymulin levels decline dramatically with age parallel to thymic involution, contributing to immunosenescence. Exogenous thymulin has been shown to restore T-cell function in aged animals, reduce autoimmune inflammation, and modulate pain (anti-nociceptive effects). Often stacked with Thymosin Alpha-1 in immune restoration protocols.",
"Adamax": "Adamax is a proprietary neuroprotective peptide blend typically combining peptides targeting BDNF, NGF, and neuroprotection pathways. Common components include BPC-157 (which crosses the blood-brain barrier in small amounts), Semax, or similar neuroactive peptides. Used for traumatic brain injury recovery, cognitive decline, and nerve regeneration support. The exact formulation varies by vendor — always verify component peptides and concentrations before use.",
"IllumiNeuro Blend": "IllumiNeuro is a vendor-specific nootropic and neuroprotective peptide blend designed for cognitive enhancement, focus, and neuroplasticity. Typical components include peptides targeting BDNF upregulation, glutamate modulation, and cerebrovascular blood flow. Users report improved clarity, faster processing speed, and enhanced memory consolidation. Formulations vary — always request a full component breakdown from the vendor before use.",
"FOXO4-DRI": "FOXO4-DRI is a modified D-retro-inverso peptide that disrupts the interaction between FOXO4 and p53 inside senescent cells. Normally, FOXO4 prevents p53 from triggering apoptosis in senescent cells — trapping them in a zombie-like state where they secrete inflammatory cytokines (SASP). FOXO4-DRI breaks this interaction, allowing p53 to trigger apoptosis specifically in senescent cells while leaving healthy cells intact. Developed at Erasmus University, it showed dramatic lifespan extension and physical function restoration in aged mice.",
"Oxytocin": "Oxytocin is the endogenous bonding hormone produced by the hypothalamus and released from the posterior pituitary. Exogenous oxytocin via intranasal spray reaches the brain rapidly, producing anxiolytic, prosocial, and anti-stress effects without the risks of synthetic anxiolytics. Research shows benefits for social anxiety, autism spectrum disorder, PTSD, eating disorder recovery, and relationship satisfaction. It also reduces cortisol under social stress and promotes wound healing. Not recommended for chronic daily use due to receptor downregulation.",
"SNAP-8": "SNAP-8 is a synthetic octapeptide analogue of the N-terminal sequence of SNAP-25. It competes with SNAP-25 for integration into the SNARE complex that triggers acetylcholine release at the neuromuscular junction — reducing muscle contraction at the skin surface. This produces a local botox-like effect that softens expression lines without injection. In clinical testing, SNAP-8 reduced wrinkle depth by up to 63%. Applied as a 4-10% concentration in serums twice daily.",
"DSIP": "Delta Sleep-Inducing Peptide (DSIP) is a nonapeptide first isolated from rabbit brain venous blood during slow-wave sleep. It promotes delta (slow-wave) sleep — the most restorative sleep stage — while reducing sleep onset latency. Research also shows it lowers cortisol and ACTH levels, blunts stress responses, and may have neuroprotective properties. Unlike standard sleep aids, DSIP does not appear to cause dependency or morning grogginess. Typically used in 5-7 night courses when resetting disrupted sleep.",
"GHK-Cu": "GHK-Cu (copper tripeptide-1) is a naturally occurring copper-binding peptide in human plasma that declines significantly with aging. It activates over 4,000 genes involved in tissue remodeling, wound healing, collagen synthesis, and anti-inflammatory signaling. Topically it is the most evidence-backed peptide for skin regeneration. Systemically it has shown anti-fibrotic effects in liver and lung tissue, BDNF upregulation, and potential anti-cancer properties via p53 pathway modulation. One of the most researched and safest peptides available.",
"GHK-Cu/KPV": "A dual peptide combination of GHK-Cu (copper tripeptide) and KPV (alpha-MSH-derived tripeptide). GHK-Cu drives tissue repair and collagen synthesis while KPV provides potent anti-inflammatory activity by blocking NF-kB signaling and reducing IL-1, IL-6, and TNF-alpha. Together they are effective for inflammatory bowel disease protocols, gut mucosal repair, and skin conditions involving both inflammation and structural damage. KPV is also antimicrobial against common skin pathogens.",
"NAD+": "Nicotinamide adenine dinucleotide (NAD+) is a coenzyme present in every cell, essential for hundreds of metabolic reactions including glycolysis, the TCA cycle, oxidative phosphorylation, and DNA repair. NAD+ levels decline 40-50% between ages 40-60. Declining NAD+ impairs sirtuin (SIRT1-7) and PARP function — critical for DNA repair and stress resistance. IV NAD+ produces rapid tissue-level repletion. Oral NR and NMN raise NAD+ through the salvage pathway. Research supports benefits in energy, cognitive function, and longevity.",
"GLOW Blend": "GLOW is a vendor-specific aesthetic and anti-aging peptide blend typically combining GHK-Cu for collagen stimulation, glutathione for skin brightness and antioxidant support, and often Thymosin Alpha-1 or Epitalon for systemic anti-aging effects. The combination targets skin quality, texture, hyperpigmentation, and systemic inflammation simultaneously. Available as topical or SC formulation depending on vendor.",
"KLOW Blend": "KLOW is a vendor-specific metabolic support blend combining peptides targeting weight management, insulin sensitivity, and energy metabolism. May include components such as MOTS-C, 5-Amino-1MQ, or GLP-1 analogues at research concentrations. Formulations vary by vendor — request full ingredient disclosure before use.",
"Glutathione": "Glutathione is the body's master antioxidant — a tripeptide (Gly-Cys-Glu) critical for neutralizing reactive oxygen species, detoxifying heavy metals and xenobiotics, recycling vitamins C and E, and regulating the immune system. Oral bioavailability of standard glutathione is poor; liposomal and sublingual formulations significantly improve absorption. IV glutathione bypasses absorption entirely and is used clinically for skin brightening (inhibits tyrosinase), liver protection, Parkinson's symptom management, and heavy metal detoxification.",
"Prostamax": "Prostamax is a Khavinson bioregulator tetrapeptide targeting prostate tissue gene expression. Like all Khavinson bioregulators, it works epigenetically — binding to chromatin in prostate cells and restoring age-related gene expression changes. It supports normal prostate cell proliferation patterns and androgen receptor function. Used in the Russian anti-aging medicine system in 10-day courses twice yearly as preventive prostate health maintenance.",
"Pinealon": "Pinealon is a Khavinson tripeptide bioregulator targeting pineal gland function — specifically melatonin production and circadian rhythm regulation. The pineal gland undergoes calcification and secretory decline with aging, contributing to sleep disruption, accelerated neurodegeneration, and immune decline. Pinealon administration in aged rats restored pineal secretory activity and improved sleep quality. Used in combination with Epitalon in advanced anti-aging bioregulator protocols.",
"Ovagen": "Ovagen is a Khavinson liver bioregulator tetrapeptide derived from liver tissue extract. It targets hepatocytes epigenetically to restore liver gene expression patterns — supporting bile acid production, xenobiotic detoxification (CYP450 enzymes), protein synthesis, and glycogen metabolism. Used in anti-aging protocols and for liver health support. Often combined with NAD+ and glutathione in hepatic restoration protocols.",
"Vesugen": "Vesugen is a Khavinson vascular bioregulator specifically designed to support endothelial cell function and blood vessel integrity. It targets smooth muscle cells and endothelial cells of the vascular wall, promoting gene expression patterns associated with healthy vascular tone and elasticity. Used in anti-aging cardiovascular protocols for people with hypertension, atherosclerosis risk, or age-related vascular decline.",
"Bronchogen": "Bronchogen is a Khavinson bioregulator tetrapeptide targeting bronchial epithelial cells. It restores gene expression in the bronchial epithelium involved in mucus clearance, ciliary function, and inflammatory regulation. Particularly useful for post-viral respiratory support, chronic bronchitis, and age-related decline in pulmonary function. Often used after respiratory illness to restore mucosal integrity.",
"Vilon": "Vilon (Lys-Glu dipeptide) is the simplest Khavinson bioregulator — a broad-spectrum immune system modulator that targets thymic, immune, and neuroendocrine gene expression. It normalizes T-cell and B-cell activity, modulates cytokine production, and has demonstrated lifespan extension in multiple animal models. Considered the foundational Khavinson bioregulator for general immune aging reversal. Used twice yearly for immune system maintenance in longevity protocols.",
"Cartalax": "Cartalax is a Khavinson bioregulator tetrapeptide derived from cartilage tissue, targeting chondrocyte gene expression. It supports collagen type II production, proteoglycan synthesis, and cartilage matrix maintenance. Used in anti-aging protocols for joint health, often stacked with BPC-157 and TB-500 for comprehensive connective tissue support. Unlike glucosamine/chondroitin, it acts at the gene expression level rather than as a substrate for cartilage synthesis.",
"Chonluten": "Chonluten is a Khavinson tripeptide bioregulator targeting both bronchial and intestinal mucosal gene expression — an unusual dual-tissue specificity reflecting the shared developmental origin of respiratory and GI mucosa. It restores secretory IgA production, tight junction integrity, and anti-inflammatory gene expression in mucosal tissues. Particularly useful for leaky gut combined with respiratory mucosal dysfunction.",
"Livagen": "Livagen is a Khavinson tetrapeptide bioregulator targeting liver and immune chromatin. It promotes DNA decondensation and gene expression restoration in aged liver and immune cells — an epigenetic mechanism rather than direct receptor binding. Research shows it restores lymphocyte activity, DNA repair capacity, and reduces spontaneous cancer incidence in aged animals.",
"Cardiogen": "Cardiogen is a Khavinson tetrapeptide bioregulator targeting cardiomyocyte gene expression. It restores the transcriptional activity of genes involved in cardiac muscle contraction, energy metabolism, and oxidative stress resistance in aged heart tissue. Animal studies showed improved cardiac output and reduced age-related cardiomyopathy. Used in anti-aging cardiovascular protocols alongside Vesugen for comprehensive cardiac support.",
"Cortagen": "Cortagen is a Khavinson bioregulator tetrapeptide targeting cerebral cortex neurons. It restores gene expression in cortical neurons involved in neurotransmitter synthesis, synaptic plasticity, and antioxidant defense. Animal studies showed improved learning, memory, and cognitive function in aged subjects. Often stacked with nootropic peptides like Semax and Selank for a comprehensive cognitive anti-aging protocol.",
"Pancragon": "Pancragon is a Khavinson pancreatic bioregulator targeting both exocrine (digestive enzyme-producing) and endocrine (insulin-producing beta cell) pancreatic tissue. It restores gene expression patterns in pancreatic cells that decline with age — supporting both digestive efficiency and blood glucose regulation. Used in longevity protocols for individuals with metabolic syndrome or age-related glucose dysregulation.",
"Thymogen": "Thymogen (alpha-glutamyl-tryptophan) is a naturally occurring dipeptide isolated from calf thymus that acts as a thymic immunomodulator. It stimulates T-lymphocyte differentiation and proliferation, enhances NK cell activity, and normalizes cytokine balance. Unlike synthetic immunostimulants, Thymogen has a regulating — not simply stimulating — effect. It can raise depressed immune function or reduce excessive autoimmune activity. Used clinically in Russia for post-chemotherapy immune recovery and chronic infection.",
"Crystagen": "Crystagen is a Khavinson bioregulator tetrapeptide targeting kidney tubular cells and bladder epithelium. It restores gene expression in urinary system cells involved in filtration efficiency, inflammation control, and tissue integrity. Used in anti-aging protocols for kidney function support and urinary tract health, particularly in aging males with declining renal function.",
"AHK-Cu": "AHK-Cu (copper tripeptide Ala-His-Lys) is a copper-binding tripeptide with a particularly strong affinity for the hair follicle dermal papilla. It activates hair follicle stem cells, promotes angiogenesis around follicles, and stimulates KGF and VEGF — the primary drivers of hair shaft production. Studies show it rivals minoxidil in follicle proliferation at equivalent concentrations. Often combined with GHK-Cu in topical hair serums for synergistic follicle support.",
"Sermorelin": "Sermorelin is a synthetic analogue of the first 29 amino acids of endogenous GHRH — the minimum sequence needed for full biological activity. It stimulates the pituitary to produce GH naturally, preserving the pulsatile release pattern and feedback mechanisms. This makes it fundamentally safer than exogenous HGH for long-term use — the pituitary self-regulates and does not atrophy. Popular in anti-aging medicine and age-related GH decline protocols. Must be injected at bedtime when endogenous GH secretion is highest.",
"SLU-PP-332": "SLU-PP-332 is a synthetic ERR-alpha/beta/gamma pan-agonist — an exercise mimetic that activates the estrogen-related receptors responsible for mitochondrial biogenesis, oxidative metabolism, and aerobic capacity. In mice, it significantly increased running endurance without training and activated genes associated with slow-twitch oxidative muscle fiber characteristics. Being studied as a therapeutic for obesity, heart failure, and muscle wasting. Currently early research stage with no established human dosing protocol.",
"Orforglipron": "Orforglipron is a non-peptide (small molecule) oral GLP-1 receptor agonist developed by Eli Lilly in Phase 3 trials for obesity and type 2 diabetes. Unlike semaglutide (a peptide requiring injection), orforglipron is a tablet taken once daily with no special storage requirements. Phase 2 data showed 14.7% body weight loss at 36 weeks — comparable to injectable semaglutide. If approved, it will dramatically improve GLP-1 therapy accessibility, eliminating the need for reconstitution, injection equipment, or cold chain storage.",
"KPV": "KPV (Lys-Pro-Val) is a C-terminal tripeptide fragment of alpha-melanocyte stimulating hormone. It exerts potent anti-inflammatory effects by blocking NF-kB nuclear translocation — reducing downstream inflammatory cytokines including IL-1beta, IL-6, and TNF-alpha. It also has direct antimicrobial activity against S. aureus, C. albicans, and other pathogens. Particularly effective for inflammatory bowel disease, psoriasis, wound healing, and colitis. Small enough to survive oral administration — uniquely suitable for gut-targeted delivery.",
"LL-37": "LL-37 is the only known member of the cathelicidin family in humans — a 37-amino acid antimicrobial peptide produced by neutrophils, macrophages, and epithelial cells. It kills bacteria, viruses, and fungi by disrupting their membranes, while simultaneously modulating the immune response. It promotes wound healing, angiogenesis, and epithelial cell migration. Deficiency in LL-37 is associated with increased susceptibility to skin infections, lung infections, and periodontal disease. Research applications include topical wound care and respiratory infection support.",
"L-Carnitine": "L-Carnitine is a naturally occurring amino acid derivative essential for fatty acid transport into the mitochondrial matrix for beta-oxidation. Without adequate carnitine, long-chain fatty acids cannot be converted to energy. IV carnitine is used clinically for primary carnitine deficiency and dialysis patients. Oral supplementation benefits people on carnitine-depleting medications, vegetarians, and those with metabolic conditions. Acetyl-L-Carnitine (ALCAR) crosses the blood-brain barrier and supports cognitive function and neuroprotection.",
"PNC-27": "PNC-27 is a peptide construct combining an MDM-2 binding domain from the p53 tumour suppressor protein with a penetratin membrane-inserting sequence. In cancer cells that overexpress MDM-2 (which inactivates p53), PNC-27 preferentially accumulates in the cancer cell membrane — forming pores that trigger membranolytic cell death specifically in tumour cells while leaving normal cells intact. Studied in pancreatic, breast, and leukemia cancer models with promising preclinical results. Highly experimental; no human clinical trials completed.",
"Cerebrolysin": "Cerebrolysin is a standardized mixture of low-molecular-weight peptides derived from porcine brain tissue that mimic the actions of endogenous neurotrophic factors (BDNF, NGF, GDNF, CNTF). Approved in 50+ countries for Alzheimer's disease, stroke rehabilitation, and traumatic brain injury. IV administration is required for therapeutic effect. Extensive RCT data shows cognitive improvement, reduced neurological deficit after stroke, and neuroprotection in Alzheimer's patients. Short infusion courses (10-20 days) are standard clinical protocol.",
"Neuroxelin Blend": "Neuroxelin is a vendor-specific neuroprotective and neuroregenerative peptide blend. Typical components target BDNF upregulation, mitochondrial protection in neurons, and anti-excitotoxic pathways. May include combinations of Semax, BPC-157 (CNS variant), or similar neuroactive peptides. Always verify the exact composition with the vendor before use.",
"Tri-Heal Blend": "Tri-Heal is a comprehensive tissue repair blend typically combining three complementary healing peptides — most commonly BPC-157, TB-500, and KPV. BPC-157 targets tendon and gut healing via GH receptor upregulation; TB-500 drives angiogenesis and cell migration via actin modulation; KPV addresses the inflammatory component that slows tissue repair. Together they cover all three phases of wound healing: inflammation, proliferation, and remodeling. Popular for chronic injuries that have not responded to single-peptide protocols.",
"Tesa Blend": "Tesa Blend is a tesamorelin-based vendor blend for GH axis stimulation and visceral fat reduction. May be combined with Ipamorelin or another GHRP to synergize GH pulse amplitude. Core mechanism is identical to pharmaceutical Tesamorelin — GHRH receptor agonism driving GH and downstream IGF-1 elevation with preferential visceral adipose reduction.",
"Wolverine Stack": "The Wolverine Stack is a comprehensive multi-peptide healing protocol designed for aggressive injury recovery. Typically includes BPC-157 (gut and tendon repair), TB-500 (angiogenesis and cell migration), and additional peptides such as GHK-Cu (tissue remodeling), KPV (inflammation), and sometimes AOD-9604 or GHRPs for metabolic support. Used by athletes with severe or chronic injuries who require faster recovery than single-peptide protocols can provide.",
}

with open('home.html', encoding='utf-8') as f:
    html = f.read()

# 1. Add desc field to each peptide in PEPTIDE_DATA
def add_desc(html, name, desc):
    pattern = r'(\{\s*name:"' + re.escape(name) + r'"[^}]+\})'
    match = re.search(pattern, html)
    if match:
        entry = match.group(0)
        if 'desc:' not in entry:
            desc_clean = desc.replace('\\', '\\\\').replace('"', '\\"')
            new_entry = entry[:-1] + ',  desc:"' + desc_clean + '" }'
            html = html[:match.start()] + new_entry + html[match.end():]
            return html, True
    return html, False

added = 0
not_found = []
for name, desc in DESC.items():
    html, ok = add_desc(html, name, desc)
    if ok:
        added += 1
    else:
        not_found.append(name)

print(f"Added descriptions to {added} peptides")
if not_found:
    print(f"Not found: {not_found}")

# 2. Update buildPeptideCard to show description and remove studies button
old_btn = "      '<button class=\"pep-idx-study-btn\" onclick=\"showView(\\'studies\\');setActiveNav(null);\">\\u2192 View Research Studies</button>' +"
new_btn = "      '' +"

# Use string replacement for the studies button line
html = html.replace(
    "      '<button class=\"pep-idx-study-btn\" onclick=\"showView(\\'studies\\');setActiveNav(null);\">→ View Research Studies</button>' +",
    "      '' +"
)

# Add description block before the dose line
old_dose = "    '<div id=\"' + id + '\" class=\"pep-idx-body\">' +"
new_dose = """    '<div id="' + id + '" class="pep-idx-body">' +
      (desc ? '<div style="background:rgba(0,245,255,0.04);border-left:3px solid rgba(0,245,255,0.35);padding:0.65rem 0.85rem;margin-bottom:0.75rem;border-radius:0 4px 4px 0;"><p style="font-family:\\'Rajdhani\\',sans-serif;font-size:0.93rem;font-weight:600;color:rgba(220,230,255,0.88);line-height:1.75;margin:0;">' + desc + '</p></div>' : '') +"""

html = html.replace(
    "    '<div id=\"' + id + '\" class=\"pep-idx-body\">' +",
    new_dose
)

# Also add desc to the variable extraction line
html = html.replace(
    "  var p = item.name, use = item.use, dose = item.dose||'See protocol notes', duration = item.duration||'Varies by goal', protocol = item.protocol||'';",
    "  var p = item.name, use = item.use, dose = item.dose||'See protocol notes', duration = item.duration||'Varies by goal', protocol = item.protocol||'', desc = item.desc||'';"
)
print("Updated buildPeptideCard")

with open('home.html', 'w', encoding='utf-8') as f:
    f.write(html)
print("Done.")
